#===============================================================================
substitutions:
  device_name: heating-floor
  device_id: heating_floor
#=============================================================================== 
esphome:
  name: heating-floor

esp32:
  board: m5stack-core2
  framework:
    type: arduino

packages:
  device_base: !include common/device_base_esp32.yaml
  heating-floor_touch: !include common/heating_floor/touchscreen.yaml
  heating-floor_display: !include common/heating_floor/display.yaml
  heating-floor_ledc: !include common/heating_floor/ledc.yaml
  heating-floor_switch: !include common/heating_floor/switch.yaml
  heating-floor_sensor: !include common/heating_floor/sensor.yaml
  heating-floor_number: !include common/heating_floor/number.yaml
  heating-floor_pzem: !include common/heating_floor/pzem.yaml
  person: !include common/person.yaml

logger:
#  level: INFO
#  baud_rate: 0
api: 
  password: !secret api_password
  
ota:

#web_server:
#  port: 80
#  include_internal: true
#  version: 2
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.148
    gateway: 192.168.1.1
    subnet: 255.255.255.0

dallas:
  - pin: GPIO33
    update_interval: 3s

time:
  - platform: homeassistant
    id: esptime_${device_id}

climate:
  - platform: thermostat
    name: Thermostat ${device_name}
    sensor: temp_floor_${device_id}                         #  После подключения датчика заменить . temp_home
    default_preset: HOME
    id: thermo_${device_id}
    heat_deadband: 0.2 °C
    heat_overrun: 0.2 °C
    min_heating_off_time: 3s
    min_heating_run_time: 3s
    max_heating_run_time: 3s
    min_idle_time: 1s
    supplemental_heating_delta: 1 °C
    heat_action:
      - switch.turn_on: ssr_${device_id}
      - switch.turn_on: sw_1_${device_id}
    supplemental_heating_action:
      lambda: !lambda |-
        if (id(thermo_${device_id}).current_temperature < (id(thermo_${device_id}).target_temperature-(id(step_2_${device_id}).state))) {id(sw_2_${device_id}).turn_on();}
          // молоко else {id(sw_2_${device_id}).turn_off();}    
        if (id(thermo_${device_id}).current_temperature < (id(thermo_${device_id}).target_temperature-(id(step_3_${device_id}).state))) {id(sw_3_${device_id}).turn_on();}
          // молоко else {id(sw_3_${device_id}).turn_off();}
    idle_action:
      - switch.turn_off: ssr_${device_id}
      - switch.turn_off: sw_1_${device_id}
      - switch.turn_off: sw_2_${device_id}
      - switch.turn_off: sw_3_${device_id}
    preset:
      - name: HOME
        default_target_temperature_low: 25 °C
      - name: AWAY
        default_target_temperature_low: 23 °C
#===============================================================================
#light:                                      # Подсветка экрана, вел/выкл
#  - platform: status_led
#    name: "Led Blue ${device_name}"
#    pin: GPIO23

